### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by LonelyGuy12** [ReplDepot/replit-cli#18]
```Traceback (most recent call last):
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\snow_pyrepl\__init__.py", line 8, in <module>
    from snow_pyrepl.api_pb2 import *
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\snow_pyrepl\api_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\Scripts\replit.exe\__main__.py", line 4, in <module>
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\repl_cli\main.py", line 4, in <module>
    import snow_pyrepl as pyrepl
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\snow_pyrepl\__init__.py", line 10, in <module>
    from snow_pyrepl import api_pb2
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\snow_pyrepl\api_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
PS C:\Users\phoen\OneDrive\Desktop> replit clone https://replit.com/@AlexPhoenix1/IroncladTightPatch
Traceback (most recent call last):
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\snow_pyrepl\__init__.py", line 8, in <module>
    from snow_pyrepl.api_pb2 import *
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\snow_pyrepl\api_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

During handling of the above exception, another exception occurred:
```

**Comment by LonelyGuy12** [comment]
Please solve

**Comment by CoolCoderSJ** [comment]
Run the following commands 
```bash
pip install python3-protobuf
pip uninstall -y python3-protobuf protobuf
pip install protobuf --upgrade
replit
```

**Comment by LonelyGuy12** [comment]
> Run the following commands
> 
> ```shell
> pip install python3-protobuf
> pip uninstall -y python3-protobuf protobuf
> pip install protobuf --upgrade
> replit
> ```

Throws one more issue
```PS C:\Users\phoen\OneDrive\Desktop> replit clone https://replit.com/@AlexPhoenix1/PointlessOutgoingEnvironment
Traceback (most recent call last):
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\Scripts\replit.exe\__main__.py", line 4, in <module>
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\repl_cli\main.py", line 840, in <module>
    app()
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\repl_cli\main.py", line 275, in clone
    downloadRepl(user, replname)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\repl_cli\main.py", line 53, in downloadRepl
    token, url = pyrepl.get_token(user, replname, key)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\snow_pyrepl\__init__.py", line 41, in get_token
    data = json.loads(r.text.split("<script id=\"__NEXT_DATA__\" type=\"application/json\">")[1].split("</script>")[0])['props']['pageProps']['connectionMetadata']
IndexError: list index out of range

```

**Comment by CoolCoderSJ** [comment]
this just means you didn't put in your repl correctly. make sure you rub the function like so

```bash
replit command slug
```

your slug is the part in your repl url after the replit.com/

for example, if my repl url is https://replit.com/@CoolCoderSJ/replit-oauth#file.py, my slug is `@CoolCoderSJ/replit-oauth `

So for example, if I wanted to clone this repl, I'd run
```bash
replit clone @CoolCoderSJ/replit-oauth
```

**Comment by 19wintersp** [comment]
Seems like a usability issue, maybe you should handle errors like this more gracefully
